
name = 'Fra';   % 'Simo' o 'Fra'

for index=1:10
    
    filename = strcat('source/raw_data/Lissone/GaitRite/', strcat(name,strcat(name, strcat('/FootDetail',strcat(name, strcat(num2str(index), '.xlsx'))))));
    [ ...
    Event_L,FirstContact_L,FootFlat_L,LastContact_L,Step_time_L,Stride_time_L,Swing_time_L, ...
    Stance_time_L,Supp_time_Double_L,Stride_velocity_L, ...
    Event_R,FirstContact_R,FootFlat_R,LastContact_R,Step_time_R,Stride_time_R,Swing_time_R, ...
    Stance_time_R,Supp_time_Double_R,Stride_velocity_R ...
    ] = importGaitRite(filename);
    
    %save(strcat('YOUR_PATH_TO_REPOSITORY_HERE\MATLAB\source\file_mat\Lissone_acquisitions\GaitRite\', strcat(name, strcat('\GR_',strcat(name, num2str(index))))));
end

name = 'Simo';   % 'Simo' o 'Fra'

for index=1:10
    
    filename = strcat('source/raw_data/Lissone/GaitRite/', strcat(name,strcat(name, strcat('/FootDetail',strcat(name, strcat(num2str(index), '.xlsx'))))));
    [ ...
    Event_L,FirstContact_L,FootFlat_L,LastContact_L,Step_time_L,Stride_time_L,Swing_time_L, ...
    Stance_time_L,Supp_time_Double_L,Stride_velocity_L, ...
    Event_R,FirstContact_R,FootFlat_R,LastContact_R,Step_time_R,Stride_time_R,Swing_time_R, ...
    Stance_time_R,Supp_time_Double_R,Stride_velocity_R ...
    ] = importGaitRite(filename);
    
    %save(strcat('YOUR_PATH_TO_REPOSITORY_HERE\MATLAB\source\file_mat\Lissone_acquisitions\GaitRite\', strcat(name, strcat('\GR_',strcat(name, num2str(index))))));
end